export const MOCK_DEALS = [
  {
    id: "1",
    marque: "BMW",
    modele: "Série 3 320d",
    annee: 2020,
    km: 68000,
    carburant: "Diesel",
    boite: "Automatique",
    prixAffiche: 22500,
    coteMarcheEstimee: 27800,
    margePotentielle: 5300,
    margePourcent: 19,
    score: 87,
    risque: "low" as const,
    source: "Leboncoin",
    localisation: "Lyon (69)",
    tempsPublication: "Il y a 2h",
    image: null,
    finition: "Sport Line",
    etat: "Très bon",
  },
  {
    id: "2",
    marque: "Volkswagen",
    modele: "Golf 8 GTI",
    annee: 2021,
    km: 41000,
    carburant: "Essence",
    boite: "Manuelle",
    prixAffiche: 28000,
    coteMarcheEstimee: 33500,
    margePotentielle: 5500,
    margePourcent: 16,
    score: 84,
    risque: "low" as const,
    source: "La Centrale",
    localisation: "Paris (75)",
    tempsPublication: "Il y a 4h",
    image: null,
    finition: "GTI",
    etat: "Excellent",
  },
  {
    id: "3",
    marque: "Mercedes",
    modele: "Classe C 220d",
    annee: 2019,
    km: 92000,
    carburant: "Diesel",
    boite: "Automatique",
    prixAffiche: 19800,
    coteMarcheEstimee: 23400,
    margePotentielle: 3600,
    margePourcent: 15,
    score: 76,
    risque: "medium" as const,
    source: "AutoScout24",
    localisation: "Marseille (13)",
    tempsPublication: "Il y a 6h",
    image: null,
    finition: "Avantgarde",
    etat: "Bon",
  },
  {
    id: "4",
    marque: "Peugeot",
    modele: "508 SW GT",
    annee: 2022,
    km: 29000,
    carburant: "Hybride",
    boite: "Automatique",
    prixAffiche: 27500,
    coteMarcheEstimee: 32000,
    margePotentielle: 4500,
    margePourcent: 14,
    score: 81,
    risque: "low" as const,
    source: "Leboncoin",
    localisation: "Bordeaux (33)",
    tempsPublication: "Il y a 1h",
    image: null,
    finition: "GT",
    etat: "Excellent",
  },
  {
    id: "5",
    marque: "Audi",
    modele: "A4 Avant 35 TDI",
    annee: 2021,
    km: 55000,
    carburant: "Diesel",
    boite: "Automatique",
    prixAffiche: 26900,
    coteMarcheEstimee: 31200,
    margePotentielle: 4300,
    margePourcent: 14,
    score: 79,
    risque: "low" as const,
    source: "Mobile.de",
    localisation: "Strasbourg (67)",
    tempsPublication: "Il y a 3h",
    image: null,
    finition: "S Line",
    etat: "Très bon",
  },
  {
    id: "6",
    marque: "Renault",
    modele: "Mégane IV RS",
    annee: 2019,
    km: 48000,
    carburant: "Essence",
    boite: "Manuelle",
    prixAffiche: 22000,
    coteMarcheEstimee: 26500,
    margePotentielle: 4500,
    margePourcent: 17,
    score: 83,
    risque: "low" as const,
    source: "Leboncoin",
    localisation: "Toulouse (31)",
    tempsPublication: "Il y a 5h",
    image: null,
    finition: "RS Trophy",
    etat: "Très bon",
  },
];

export const MOCK_HISTORY = [
  {
    id: "h1",
    date: "2024-01-22",
    marque: "BMW",
    modele: "M2 Competition",
    prix: 48500,
    cote: 55000,
    score: 88,
    recommandation: "ACHETER" as const,
  },
  {
    id: "h2",
    date: "2024-01-21",
    marque: "Mercedes",
    modele: "AMG A 45 S",
    prix: 42000,
    cote: 44500,
    score: 52,
    recommandation: "NÉGOCIER" as const,
  },
  {
    id: "h3",
    date: "2024-01-20",
    marque: "Audi",
    modele: "RS3 Berline",
    prix: 51000,
    cote: 53000,
    score: 45,
    recommandation: "PASSER" as const,
  },
  {
    id: "h4",
    date: "2024-01-19",
    marque: "Volkswagen",
    modele: "Golf R",
    prix: 36000,
    cote: 41500,
    score: 82,
    recommandation: "ACHETER" as const,
  },
];

export const MOCK_STATS = {
  analysesTotal: 142,
  margeMoyenne: 3840,
  meilleureAffaire: 8200,
  tauxSucces: 73,
};

export const MARQUES = [
  "Audi", "BMW", "Citroën", "Dacia", "DS", "Fiat", "Ford", "Honda",
  "Hyundai", "Jaguar", "Kia", "Land Rover", "Lexus", "Maserati", "Mazda",
  "Mercedes", "Mini", "Mitsubishi", "Nissan", "Opel", "Peugeot", "Porsche",
  "Renault", "Seat", "Skoda", "Suzuki", "Tesla", "Toyota", "Volkswagen", "Volvo",
];

export const FINITIONS: Record<string, string[]> = {
  BMW: ["Base", "Sport Line", "M Sport", "M Sport Pro", "Individual"],
  Mercedes: ["Standard", "Avantgarde", "AMG Line", "AMG", "Brabus"],
  Volkswagen: ["Trendline", "Comfortline", "Highline", "R-Line", "GTI", "GTD", "R"],
  Audi: ["Base", "S Line", "Sport", "S", "RS"],
  Renault: ["Life", "Zen", "Business", "Intens", "RS", "RS Trophy"],
  Peugeot: ["Active", "Allure", "GT Line", "GT", "SW"],
  default: ["Base", "Confort", "Business", "Premium", "Sport", "Exclusive"],
};
